// <auto-generated />
using System;
using BazaarCompanionWeb.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BazaarCompanionWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFMarketData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BookValue")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<int>("OrderVolume")
                        .HasColumnType("integer");

                    b.Property<double>("OrderVolumeWeek")
                        .HasColumnType("double precision");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("EFMarketData", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFOhlcCandle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AskClose")
                        .HasColumnType("double precision");

                    b.Property<double>("Close")
                        .HasColumnType("double precision");

                    b.Property<double>("High")
                        .HasColumnType("double precision");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<double>("Low")
                        .HasColumnType("double precision");

                    b.Property<double>("Open")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("Spread")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Interval", "PeriodStart");

                    b.HasIndex("ProductKey", "Interval", "PeriodStart")
                        .IsUnique();

                    b.ToTable("EFOhlcCandles", (string)null);
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFOrderBookSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AskOrderCount")
                        .HasColumnType("integer");

                    b.Property<int>("AskVolume")
                        .HasColumnType("integer");

                    b.Property<int>("BidOrderCount")
                        .HasColumnType("integer");

                    b.Property<int>("BidVolume")
                        .HasColumnType("integer");

                    b.Property<double>("PriceLevel")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ProductKey", "Timestamp");

                    b.ToTable("EFOrderBookSnapshots", (string)null);
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFPriceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AskUnitPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("BidUnitPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("Taken")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProductKey");

                    b.ToTable("EFPriceSnapshots", (string)null);
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFPriceTick", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AskPrice")
                        .HasColumnType("double precision");

                    b.Property<long>("AskVolume")
                        .HasColumnType("bigint");

                    b.Property<double>("BidPrice")
                        .HasColumnType("double precision");

                    b.Property<long>("BidVolume")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductKey", "Timestamp");

                    b.ToTable("EFPriceTicks", (string)null);
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFProduct", b =>
                {
                    b.Property<string>("ProductKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SkinUrl")
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<bool>("Unstackable")
                        .HasColumnType("boolean");

                    b.HasKey("ProductKey");

                    b.HasIndex("LastSeenAt");

                    b.ToTable("EFProducts", (string)null);
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFProductMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("FlipOpportunityScore")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsManipulated")
                        .HasColumnType("boolean");

                    b.Property<double>("ManipulationIntensity")
                        .HasColumnType("double precision");

                    b.Property<double>("PriceDeviationPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("ProfitMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("Spread")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalWeekVolume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ProductKey")
                        .IsUnique();

                    b.ToTable("EFProductMetas", (string)null);
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFAskMarketData", b =>
                {
                    b.HasBaseType("BazaarCompanionWeb.Entities.EFMarketData");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasIndex("ProductKey")
                        .IsUnique();

                    b.ToTable("EFAskMarketData", (string)null);
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFBidMarketData", b =>
                {
                    b.HasBaseType("BazaarCompanionWeb.Entities.EFMarketData");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasIndex("ProductKey")
                        .IsUnique();

                    b.ToTable("EFBidMarketData", (string)null);
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFOhlcCandle", b =>
                {
                    b.HasOne("BazaarCompanionWeb.Entities.EFProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFPriceSnapshot", b =>
                {
                    b.HasOne("BazaarCompanionWeb.Entities.EFProduct", "Product")
                        .WithMany("Snapshots")
                        .HasForeignKey("ProductKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFPriceTick", b =>
                {
                    b.HasOne("BazaarCompanionWeb.Entities.EFProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFProductMeta", b =>
                {
                    b.HasOne("BazaarCompanionWeb.Entities.EFProduct", "Product")
                        .WithOne("Meta")
                        .HasForeignKey("BazaarCompanionWeb.Entities.EFProductMeta", "ProductKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFAskMarketData", b =>
                {
                    b.HasOne("BazaarCompanionWeb.Entities.EFMarketData", null)
                        .WithOne()
                        .HasForeignKey("BazaarCompanionWeb.Entities.EFAskMarketData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BazaarCompanionWeb.Entities.EFProduct", "Product")
                        .WithOne("Ask")
                        .HasForeignKey("BazaarCompanionWeb.Entities.EFAskMarketData", "ProductKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFBidMarketData", b =>
                {
                    b.HasOne("BazaarCompanionWeb.Entities.EFMarketData", null)
                        .WithOne()
                        .HasForeignKey("BazaarCompanionWeb.Entities.EFBidMarketData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BazaarCompanionWeb.Entities.EFProduct", "Product")
                        .WithOne("Bid")
                        .HasForeignKey("BazaarCompanionWeb.Entities.EFBidMarketData", "ProductKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BazaarCompanionWeb.Entities.EFProduct", b =>
                {
                    b.Navigation("Ask")
                        .IsRequired();

                    b.Navigation("Bid")
                        .IsRequired();

                    b.Navigation("Meta")
                        .IsRequired();

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
